- app/assets/stylesheets/discuss.scss
- app/controllers/discusses_controller.rb
- app/views/discusses/main_form.html.erb
Change course rating style from star to square-bar and remove surplus config
> Change course rating style

- app/assets/javascripts/courses/table.js
修改
模擬選課系統有BUG
若從課表的share網址中點選任一課程詳細資訊
會進錯網址
的bug
> Fix redirect error

- app/controllers/newcomer_controller.rb
> Update newcomer studentAssociation data

- app/views/newcomer/procedure.html.erb
- 在新生包初入交大頁面新增很重要的「繳費」行程
- 在新生包初入交大頁面刪除不需要的「士林卡」行程
> Update newcomer procedure

- app/helpers/user_helper.rb
- app/views/user/show.html.erb
- config/routes.rb
*course_map_link button
*rename "GPA 計算機" to "GPA 計算"
> Add a course_map_link button on user page

- app/controllers/scores_controller.rb
* modify the imported rules on deleting all the current_user.nomal_scores
* seek all around the imported course to check if there have courses
which semester_id is equal to Semesrer::LAST.id
=> if true then delete all the current_user.normal_scores
=> if not then delete all the current_user.normal_scores except for the
current semester course
> Fix the import of the courses will cause the deletion of simulation(No FORMAT adjestment!!!)

- app/controllers/scores_controller.rb
> Fix import bug2

- app/controllers/courses_controller.rb
* Change to use course-name instead of course_detail_id
* Avoid to recommend trivial courses e.g.'導師時間'
> Modify students who took this course also took

- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/courses_controller.rb
- app/models/course_detail.rb
- app/views/courses/index.html.erb
- app/views/courses/search/_mini_form.html.erb
- app/views/courses/search/_search_js.html.erb
- config/initializers/ransack.rb
Now user can select all options in 模擬排課 and 全校課程.
> Select all options in Course search and indentation fixing

- app/controllers/bulletin_controller.rb
- app/controllers/main_controller.rb
- app/controllers/slogan_controller.rb
- app/models/bulletin.rb
- app/views/bulletin/_form.html.erb
- app/views/bulletin/edit.html.erb
- app/views/bulletin/index.html.erb
- app/views/bulletin/new.html.erb
- app/views/slogan/_form.html.erb
- app/views/slogan/edit.html.erb
- app/views/slogan/index.html.erb
- app/views/slogan/new.html.erb
- db/migrate/20170130070421_add_begin_end_time_to_bulletin.rb
- db/migrate/20170130090318_add_hidden_type_to_slogan.rb
- db/migrate/20170131153409_add_begin_end_time_to_bulletin.rb
- db/schema.rb
add hidden_type column to slogan to determine whether it will show or not.
add begin_time and end_time to bulletin to schedule bulletins.
> Bulletin schedule

- app/models/auth_nctu.rb
NCTU OAuth change the name of email field
> Modify d2_email to email in NCTU OAuth

- app/controllers/books_controller.rb
- app/views/books/index.html.erb
- config/routes.rb
Fix the bug that user can't set books saled.
> Use post to set book saled

- app/views/books/_index_book_grid.html.erb
- app/views/books/_modal.html.erb
- app/views/books/index.html.erb
> Use bootstrap modal replace confirm to resolve Firefox wrong redirect

- config/initializers/devise.rb
- db/schema.rb
Fix login problem with omniauth-facebook
[reference](https://github.com/gregoryjpark/threegoodthings/pull/187)
> Fix login problem with omniauth-facebook

- app/views/discusses/list_by_ct.html.erb
> BugFix/Avatar In CourseDiscuss Is Wrong

- lib/tasks/course.rake
> Update the import semester

- app/assets/javascripts/user_course_stat/checker.js
fix common course "群己" vs. "群已" bug at user page.
> Fix common course bug at user page

- app/assets/javascripts/calendar/add-event.js
- app/assets/javascripts/calendar/calendar.js
- app/assets/javascripts/calendar/tag-bell.js
- app/assets/javascripts/calendar/tag-cale.js
> Fix precompile error remove usage of backtick in js

- app/views/calendar/index.html.erb
- config/initializers/assets.rb
> Try to fix .css not found problem which is wierd

- app/assets/javascripts/courses/table.js
- app/views/courses/search/_mini_form.html.erb
> Fix simulation

- app/assets/javascripts/courses/simulation.js
- app/assets/javascripts/courses/table.js
- app/assets/stylesheets/course.css.scss
- app/views/courses/simulation.html.erb
- app/views/user/show.html.erb
Also:
1. 修正模擬排課頁面(simulation)上方的提醒，以便手機版觀看
2. 修改上述提醒的文字內容
3. 在個人頁面(user)也添加類似提醒，提示可以由該table上的按鈕連結到該課程頁面填寫課程回饋
> Ajust styles of links in course table

- app/controllers/user_controller.rb
- lib/tasks/course.rake
> Hotfix issue84

- app/views/course_content/_scroll_sidebar.html.erb
修正chrome在course show 的時候按側欄沒辦法滾動的情況。
> Hotfix courses show sidebar

- app/views/course_maps/public/_xtmpl_course_table.html.erb
- app/views/course_maps/show.html.erb
Fix courses showed in wrong semester
> 修復課程地圖裡課程顯示位置錯誤

- app/assets/javascripts/courses/html2canvas.js
- app/assets/javascripts/courses/table.js
> 原本想把html2canvas這個套件更新到最新的版本，但最後覺得相依的部分可能偏多，所以還是直接修改原先v0.4.1
- 強制讓輸出的課表背景有底色，雖然解析度還是無法達到最新版本的套件，但還堪用。
- 把匯出的檔名變得比較有意義
> 修改匯出課表的一些問題

- app/helpers/course_helper.rb
學校匯入的資料中 體育課的cos_type由原本的必修改為體育，所以讓course_helper增加這個判斷
> 讓course_helper支援cos_type為體育時判斷為必修

- app/views/events/index.html.erb
> 更改html語法錯誤

- app/controllers/discusses_controller.rb
- app/views/discusses/main_form.html.erb
> 在新增心得內放入預設輸入值

- app/views/courses/search/_mini_form.html.erb
> 修正進階搜尋(模擬排課)

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/views/courses/simulation.html.erb
- app/views/user/show.html.erb
直接創了一個新的branch , 因為上次(#76 )太舊了
直接改使用其他gem 套件
> 修正複製剪貼簿的按鈕

- app/views/layouts/_header.html.erb
> remove entrypoint for newcomer from header

- app/views/layouts/_header.html.erb
在Navbar中新增個人資料連結
給使用者多一個更明顯的選項
> 新增使用者個人資料連結

- app/views/courses/search/_undergrad_options.html.erb
> Add missing department
